# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('temp', models.FloatField(default=None)),
                ('weight', models.FloatField(default=None)),
                ('circum', models.FloatField(default=None)),
                ('date', models.CharField(default=None, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l', models.FloatField(default=0)),
                ('a', models.FloatField(default=0)),
                ('b', models.FloatField(default=0)),
                ('gar', models.FloatField(default=0)),
                ('picture_name', models.CharField(default='', max_length=64)),
                ('general_data', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.GeneralData')),
            ],
        ),
        migrations.CreateModel(
            name='PomeloIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(default=None, max_length=5)),
                ('description', models.CharField(default=None, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PomeloSubIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sub_symbol', models.CharField(default=None, max_length=5)),
                ('pomelo_index', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.PomeloIndex')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='pomelo_sub_index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.PomeloSubIndex'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='pomelo_index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.PomeloIndex'),
        ),
    ]
