# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='date',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='information',
            name='picture_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
