# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='general_data',
        ),
        migrations.RemoveField(
            model_name='information',
            name='pomelo_sub_index',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
