# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20171125_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('l', models.FloatField(default=0)),
                ('a', models.FloatField(default=0)),
                ('b', models.FloatField(default=0)),
                ('gar', models.FloatField(default=0)),
                ('picture_name', models.CharField(default='', max_length=64)),
                ('general_data', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.GeneralData')),
                ('pomelo_sub_index', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.PomeloSubIndex')),
            ],
        ),
    ]
