# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20171124_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='pomelo_sub_index',
        ),
        migrations.AddField(
            model_name='information',
            name='general_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.GeneralData'),
        ),
    ]
