# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20171124_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='pomelo_sub_index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.PomeloSubIndex'),
        ),
    ]
